FORMAT: 1A
HOST: https://synctest.stratafleet.com/api

# StrataSync

StrataSync is a simple API allowing operators to upload the schedule of their aircraft to StrataFleet.


**This API requires an API key provided by Stratajet to be consumed.**

___
Please contact the integration team if you have any questions:

<!--Live chat on Gitter: https://gitter.im/Stratajet/StrataSync-->

- Using our [Slack live chat support](http://stratajet.slack.com 'Stratajet on slack') ( **recommended**, you should have received an invitation, if not please notify us!)
- Email: integrations@stratajet.com
- Tel: +44 203 397 4612



## Technical Introduction

- Sandbox environment: https://<span></span>synctest.stratafleet.com/api
- Production environment: https://<span></span>sync.stratafleet.com/api

The API accepts and returns both `JSON` and `XML` (content type needs to be specified in the request header). There are multiple ways of uploading your schedule, you can use [RESTful](https://en.wikipedia.org/wiki/Representational_state_transfer 'Rest on wikipedia') actions or *bulk* actions to upload multiple events at a time.

Code samples are available for every action and in a large variety of programming languages. To display a code sample, click on an action and then click on the dropdown ("Raw" is selected by default):
![create an event link](https://github.com/Stratajet/stratasync-blueprint-apidoc/blob/master/Screen%20Shot%202016-11-09%20at%2015.11.08.png?raw=true)

![language dropdown](https://github.com/Stratajet/stratasync-blueprint-apidoc/blob/master/Screen%20Shot%202016-11-09%20at%2015.13.43.png?raw=true)

> Note that *Production* in the dropdown list actually points to a *production-like* server, but not the actual live system. Unfortunately, we are not able to change the label. This testing server can be slower than the real production server.

## Required HTTP headers

| Header  | Example value | Description
| ------------- | ------------- | ------------- |
| Authorization | Token token=72831808-3e6d-4dca-8a38-0f9e068873a0 | API key provided by Stratajet
| Content-Type  | text/xml  | Format of the request body 
| Accept  | application/json  | Desired format of the response body


## HTTP Codes

Here is the list of possible codes returned by the API and their description

| HTTP Code  | Description
| ------------- | ------------- | ------------- |
| 200 | OK |
| 201  | The resource was successfully created |
| 202 | Accepted. The request is processed in the background |
| 400 | Bad request. The server didn't understand the submitted payload |
| 401 | Unauthorized. The token was not found in the header or was incorrect |
| 403 | Forbbiden. The server is responding but refuses to take any further action |
| 404 | Not found. Couldn't find the resource described by the URI |
| 409 | Conflict. Typically when trying to create an event with an when another already exists with the same `data_source_unique_id` |
| 422 | Unprocessable Entity. The request was well-formed but was unable to be followed due to semantic errors See the error list below |
| 5xx | Server Error. Something went wrong. We were notified in case of a 500. Please contact the support if necessary |



## Event error list (HTTP 422)
These are the possible errors when receiving an *Unprocessable Entity* error (422), which could be useful to debug your requests.

| Error |
| ------------- |
| Utilization XXX is an invalid use |
| Aircraft can't be blank |
| Arrival time can't be blank |
| Arrival time format must be yyyy-mm-ddThh:mmZ |
| Departure time can't be blank |
| Departure time format must be yyyy-mm-ddThh:mmZ |
| Data source unique can't be blank |
| Utilization count is not a number |
| From airfield is not a valid ICAO code |
| To airfield is not a valid ICAO code |



## Events [/events]

## RESTful actions
 Real time updates of single events. **This is the best choice** if you can update the source code of your scheduler application.
 We recommend that you use asynchronous HTTP calls or delay the request in a job queue (for example) so that potential network issues will not impact the performance of your application. These endpoints give you real-time feedback about the validity of the data submitted.

+ Attributes
    + id: `1234` (number) - The Stratajet internal id of the event, returned upon creation of a single event. To be used in further *RESTful* requests.
    + data_source_unique_id: `550e8400-e29b-41d4-a716-446655440000` (string, required) - The unique identifier used by the integration provider to identify the event. We recommend using UUID but any other unique identifier can be used instead. **Must be a unique id in your scheduling software**.
    + registration_mark: `G-ABCD` (string, required) - The registration mark of the aircraft involved in the event. **If it doesn't exist upon creation of the event, a new aircraft will be created with the registration mark provided.**
    + start_time: `2016-06-01T12:00Z` (string, required) - The start time of an aircraft event, in zulu.
    + end_time: `2016-06-01T14:00Z` (string, required) - The end time of an aircraft event, in zulu.
    + start_airfield: `EGTK` (string, required) - ICAO code representing the location of the aircraft at the start of the event.
    + end_airfield: `LFPB` (string, required) - ICAO code representing the location of the aircraft at the end of the event. Can be the same as start airfield.
    + utilization: `PAX` (enum[string], required) - A string representing the activity of the aircraft. 
      + Members
        + `CARGO` - Aircraft is carrying cargo.
        + `EMPTY` - Aircraft is flying with no passengers and __can be replaced__ with a revenue flight
        + `MAINTENANCE` - Aircraft is undergoing maintenance
        + `OPERATIONAL` - Aircraft is being used for a flight that is not replaceable
        + `OPTION` - Aircraft has been optioned, but not confirmed. For all intents and purposes, this type of event is ignored
        + `PAX` - Aircraft is flying with passengers
        + `PRIVATE` - Aircraft is being used by the owner
        + `TRAINING` - Aircraft is being used for training
        + `UNCLASSIFIED` - Aircraft is being used for an unspecified purpose
    + utilization_count (number, required) - If the utilization is cargo, the value is the weight of cargo in kg. Otherwise, the value indicate the number of passengers
    + deleted (boolean, required) - Indicates whether an aircraft event has been deleted. Ie. it has been previously submitted to the webservice, but has since been removed.


### Show an event [GET /events/{id}]
*Note: This "Show" action is not currently available in production for security reasons.*

+ Parameters
    + id: `42` (number, required) - Id of an event.
    
+ Request (application/json)

    + Headers

            Authorization: Token token=YOUR_TOKEN
            Accept: application/json

+ Response 200 (application/json)

            {
                "event": {
                    "id": 42,
                    "registration_mark": "X-XXXX",
                    "start_time": "2016-06-01T12:00Z",
                    "end_time": "2016-06-01T14:00Z",
                    "start_airfield": "EGTK",
                    "end_airfield": "LFPB",
                    "utilization": "PAX",
                    "utilization_count": 2,
                    "deleted": false,
                    "data_source_unique_id": "550e8400-e29b-41d4-a716-446655440000"
                }
            } 

+ Response 401 (application/json)
    **Unauthorized**. When the token is missing or incorrect.

    + Body

            {
               "message": "unauthorized"
            }


+ Response 403
    **Forbbiden**. When trying to access this action on the production server.
    
    + Body

            {
               "message": "forbbiden"
            }

 
+ Response 404 (application/json)
  **Not found**. When the event identified in the URL is doesn't exist.
  
      + Body

+ Request (text/xml)

   + Headers

            Authorization: Token token=YOUR_TOKEN
            Accept: text/xml

    
+ Response 200 (text/xml)

        <?xml version="1.0" encoding="UTF-8" ?>
        <event>
            <id type="integer">42</id>
            <registration_mark>X-XXXX</registration_mark>
            <start_time type="datetime">2016-06-01T12:00Z</start_time>
            <end_time type="datetime">2016-06-01T14:00Z</end_time>
            <start_airfield>EGTK</start_airfield>
            <end_airfield>LFPB</end_airfield>
            <utilization>PAX</utilization>
            <utilization_count type="integer">2</utilization_count>
            <deleted type="boolean">false</deleted>
            <data_source_unique_id>550e8400-e29b-41d4-a716-446655440000</data_source_unique_id>
        </event>


+ Response 401 (text/xml)
    **Unauthorized**. When the token is missing or incorrect.

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <message>unauthorized</message>
            </hash>



+ Response 403 (text/xml)
    **Forbbiden**. When trying to access this action on the production server.
    
    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <message>forbidden</message>
            </hash>
 
+ Response 404 (text/xml)
  **Not found**. When the event identified in the URL is doesn't exist.
  
      + Body


### Create an event [POST]

You may create a single event using this action. It takes a `JSON` or a `XML` object containing the details and your own identifier (must be unique).
    
+ Request (application/json)

    + Headers

            Authorization: Token token=YOUR_TOKEN
            Accept: application/json

    + Body

            {
                "event": {
                    "registration_mark": "X-XXXX",
                    "start_time": "2016-06-01T12:00Z",
                    "end_time": "2016-06-01T14:00Z",
                    "start_airfield": "EGTK",
                    "end_airfield": "LFPB",
                    "utilization": "PAX",
                    "utilization_count": 2,
                    "deleted": false,
                    "data_source_unique_id": "550e8400-e29b-41d4-a716-446655440000"
                }
            } 



+ Response 201 (application/json)
    **Created**. When the event was successfully created

    + Headers

              Location: /events/42

    + Body

            {
                "event": {
                    "id": 42,
                    "registration_mark": "X-XXXX",
                    "start_time": "2016-06-01T12:00Z",
                    "end_time": "2016-06-01T14:00Z",
                    "start_airfield": "EGTK",
                    "end_airfield": "LFPB",
                    "utilization": "PAX",
                    "utilization_count": 2,
                    "deleted": false,
                    "data_source_unique_id": "550e8400-e29b-41d4-a716-446655440000"
                }
            }


+ Response 401 (application/json)
    **Unauthorized**. When the token is missing or incorrect.

    + Body

            {
               "message": "unauthorized"
            }

+ Response 409 (application/json)
    **Conflict**. When trying to create an event that already exists (based on the `data_source_unique_id`)
    
    + Body

            {
                "message": "conflict"
            }

+ Response 422 (application/json)
  **422** Unprocessable entity. When the request was understood by the server but was semantically incorrect. Here is a list of possible error strings :
  - Utilization XXX is an invalid use
  - Aircraft can't be blank
  - Arrival time can't be blank
  - Arrival time format must be yyyy-mm-ddThh:mmZ
  - Departure time can't be blank
  - Departure time format must be yyyy-mm-ddThh:mmZ
  - Data source unique can't be blank
  - Utilization count is not a number
  - From airfield is not a valid ICAO code
  - To airfield is not a valid ICAO code

    + Body

            {
              "errors": [
                {"details" : "Aircraft can't be blank"}, 
                {"details" : "To airfield is not a valid ICAO code"},
                {"details" : "Arrival time format must be yyyy-mm-ddThh:mmZ"}
              ]
            }

+ Request (text/xml)

   + Headers

            Authorization: Token token=YOUR_TOKEN
            Accept: text/xml

    + Body

            <?xml version="1.0" encoding="UTF-8" ?>
            <event>
                <registration_mark>X-XXXX</registration_mark>
                <start_time>2016-06-01T12:00Z</start_time>
                <end_time>2016-06-01T14:00Z</end_time>
                <start_airfield>EGTK</start_airfield>
                <end_airfield>LFPB</end_airfield>
                <utilization>PAX</utilization>
                <utilization_count>2</utilization_count>
                <deleted>false</deleted>
                <data_source_unique_id>550e8400-e29b-41d4-a716-446655440000</data_source_unique_id>
            </event>

+ Response 201 (text/xml)
    **Created**. When the event was successfully created

    + Headers

              Location: /events/42


    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <event>
                <id type="integer">42</id>
                <data-source-unique-id>550e8400-e29b-41d4-a716-123</data-source-unique-id>
                <deleted type="boolean">false</deleted>
                <end-time type="datetime">2016-06-01T14:00:00Z</end-time>
                <id type="integer">376041</id>
                <registration-mark>X-XXXX</registration-mark>
                <start-airfield>EGTK</start-airfield>
                <start-time type="datetime">2016-06-01T12:00:00Z</start-time>
                <utilization>PAX</utilization>
                <utilization-count type="integer">2</utilization-count>
            </event>

+ Response 401 (text/xml)
    **Unauthorized**. When the token is missing or incorrect.

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <message>unauthorized</message>
            </hash>

+ Response 409 (text/xml)
    **Conflict**. When trying to create an event that already exists (based on the `data_source_unique_id`)
    
    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <message>conflict</message>
            </hash>


+ Response 422 (text/xml)
    **Unprocessable entity**. See the list of possible errors above.

    + Body 

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <errors type="array">
                    <error>
                        <details>Aircraft can't be blank</details>
                    </error>
                    <error>
                        <details>Arrival time format must be yyyy-mm-ddThh:mmZ</details>
                    </error>
                    <error>
                        <details>To airfield is not a valid ICAO code</details>
                    </error>
                </errors>
            </hash>


### Update an event [PUT /events/{id}]

You may partially update a single event using this action. It takes a `JSON` or `XML` object containing the attributes to update and returns the updated resource. 
You can use this action to delete an event by passing the attribute `"deleted": true`.

> __To update an event using the external id `data_source_unique_id`, you can use the endpoint `PUT /events/ext/:uid`, which behave in the exact same way__

+ Parameters
    + id: `42` (number, required) - Id of an event.

+ Request (application/json)

    + Headers

            Authorization: Token token=YOUR_TOKEN
            Accept: application/json

    + Body

            {
                "event": {
                    "start_time": "2016-06-01T13:00Z",
                    "end_time": "2016-06-01T15:00Z",
                    "start_airfield": "EGSH",
                    "utilization_count": 3
                }
            } 

+ Response 200 (application/json)
    **OK** When the resource was successfully updated.

    + Headers

            Location: /events/42

    + Body

            {
               "event": {
                    "id": 42,
                    "registration_mark": "X-XXXX",
                    "start_time": "2016-06-01T13:00Z",
                    "end_time": "2016-06-01T15:00Z",ques
                    "start_airfield": "EGSH",
                    "end_airfield": "LFPB",
                    "utilization": "PAX",
                    "utilization_count": 3,
                    "deleted": false,
                    "data_source_unique_id": "550e8400-e29b-41d4-a716-446655440000"
                }
            }


+ Response 401 (application/json)
    **Unauthorized**. When the token is missing or incorrect.

    + Body

            {
               "message": "unauthorized"
            }



+ Response 404 (application/json)
  **Not found**. When the event identified in the URL is doesn't exist.
  
      + Body


+ Response 422 (application/json)
  **Unprocessable entity**. When the payload submitted doesn't allow to update the event. Here is a list of possible error strings :
  - Utilization XXX is an invalid use
  - Aircraft can't be blank
  - Arrival time can't be blank
  - Arrival time format must be yyyy-mm-ddThh:mmZ
  - Departure time can't be blank
  - Departure time format must be yyyy-mm-ddThh:mmZ
  - Data source unique can't be blank
  - Utilization count is not a number
  - From airfield is not a valid ICAO code
  - To airfield is not a valid ICAO code


    + Body

            {
                "errors": 
                [
                    {details: "Departure time can't be blank"},
                    {details: "Utilization count is not a number"},
                ]
            }


+ Request (text/xml)

    + Headers

            Authorization: Token token=YOUR_TOKEN
            Accept: text/xml

    + Body

            <?xml version="1.0" encoding="UTF-8" ?>
            <event>
                <start_time>2016-06-01T13:00Z</start_time>
                <end_time>2016-06-01T15:00Z</end_time>
                <start_airfield>EGSH</start_airfield>
                <utilization_count>3</utilization_count>
            </event>


+ Response 200 (text/xml)
    **OK** When the resource was successfully updated.

    + Headers

            Location: /events/42

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <event>
                <data-source-unique-id>550e8400-e29b-41d4-a716-446655440000</data-source-unique-id>
                <deleted type="boolean">true</deleted>
                <end-time type="datetime">2016-06-01T15:00:00Z</end-time>
                <id type="integer">367229</id>
                <registration-mark>CS-DTQ</registration-mark>
                <start-airfield>EGSH</start-airfield>
                <start-time type="datetime">2016-06-01T13:00:00Z</start-time>
                <utilization>MAINTENANCE</utilization>
                <utilization-count type="integer">3</utilization-count>
            </event>



+ Response 401 (text/xml)
    **Unauthorized**. When the token is missing or incorrect.

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <message>unauthorized</message>
            </hash>

 
+ Response 404 (text/xml)
  **Not found**. When the event identified in the URL is doesn't exist.
  
      + Body



+ Response 422 (application/json)
  **Unprocessable entity**. When the payload submitted doesn't allow to update the event. See above for the list of possible errors

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <errors type="array">
                    <error>
                        <details>Utilization count is not a number</details>
                    </error>
                    <error>
                        <details>From airfield is not a valid ICAO code</details>
                    </error>
                </errors>
            </hash>


## Schedule - bulk actions [/schedules]
This is a set of convenient actions to update the schedule with bulk actions (multiple events). The events submitted will be processed by a background job and may not be immediately available.

### Update the schedule [PUT]

This action is not as ideal as the RESTful real-time solution, but can be easier to implement.

This method can be implemented without modifying your scheduler application, i.e. you can develop another program or add a dataflow to your ETL platform that periodically extracts the changes from the database since the last job run. You would typically need a timestamp to track creations and modifications, and a unique identifier for each event.

 > You also need to include deleted/cancelled events in the payload, with the attribute `deleted` set to `true`.

+ Request (application/json)

    + Headers

            Authorization: Token token=YOUR_TOKEN
            Accept: application/json

    + Body

            {
                "schedule":
                {
                    "events": 
                    [
                        {
                            "registration_mark": "X-XXXX",
                            "start_time": "2016-06-01T13:00Z",
                            "end_time": "2016-06-01T15:00Z",
                            "start_airfield": "EGSH",
                            "end_airfield": "LFPB",
                            "utilization": "PAX",
                            "utilization_count": 3,
                            "deleted": false,
                            "data_source_unique_id": "550e8400-e29b-41d4-a716-446655440000"
                        },
                        {
                            "registration_mark": "X-XXXX",
                            "start_time": "2016-06-03T09:00Z",
                            "end_time": "2016-06-03T11:30Z",
                            "start_airfield": "EBBR",
                            "end_airfield": "EGTK",
                            "utilization": "EMPTY",
                            "utilization_count": 0,
                            "deleted": false,
                            "data_source_unique_id": "660e8400-e29b-41d4-a716-4466554412324"
                        },
                        {
                            "registration_mark": "X-XXXX",
                            "start_time": "2016-07-04T09:00Z",
                            "end_time": "2016-07-04T11:30Z",
                            "start_airfield": "LFPB",
                            "end_airfield": "EBBR",
                            "utilization": "PAX",
                            "utilization_count": 1,
                            "deleted": true,
                            "data_source_unique_id": "770e8400-e29b-41d4-a716-4466554415678"
                        }
                    ]
                }
            } 

+ Response 202 (application/json)
    **Accepted**. The request to create the schedule has been accepted for processing

    + Body
    
+ Response 400
    **Bad request**. Invalid payload.

    + Headers

            Content-Type: application/json

    + Body

            {
              "message": "Invalid payload. The array of events was not provided or was empty"
            }

+ Response 401 (application/json)
    **Unauthorized**. When the token is missing or incorrect.

    + Body

            {
               "message": "unauthorized"
            }


+ Response 422
    **Unprocessable Entity**. Some of the events submitted were not valid. A list of error will be returned as shown below.

    + Body

            {
                "errors": 
                [
                    {
                        "details" : "Aircraft can't be blank",
                        "meta": {"index": 42}
                    }
                ]
              }
              

+ Request (text/xml)

    + Headers

            Accept: text/xml
            Authorization: Token token=YOUR_TOKEN

    + Body

            <schedule>
                <events>
                    <event>
                        <registration_mark>X-XXXX</registration_mark>
                        <start_time>2016-06-01T13:00Z</start_time>
                        <end_time>2016-06-01T15:00Z</end_time>
                        <start_airfield>EGSH</start_airfield>
                        <end_airfield>LFPB</end_airfield>
                        <utilization>PAX</utilization>
                        <utilization_count>3</utilization_count>
                        <deleted>false</deleted>
                        <data_source_unique_id>550e8400-e29b-41d4-a716-4466554412333</data_source_unique_id>
                    </event>
                    <event>
                        <registration_mark>X-XXXX</registration_mark>
                        <start_time>2016-06-03T09:00Z</start_time>
                        <end_time>2016-06-03T11:30Z</end_time>
                        <start_airfield>EBBR</start_airfield>
                        <end_airfield>EGTK</end_airfield>
                        <utilization>EMPTY</utilization>
                        <utilization_count>0</utilization_count>
                        <deleted>false</deleted>
                        <data_source_unique_id>660e8400-e29b-41d4-a716-4466554412324</data_source_unique_id>
                    </event>
                    <event>
                        <registration_mark>X-XXXX</registration_mark>
                        <start_time>2016-07-04T09:00Z</start_time>
                        <end_time>2016-07-04T11:30Z</end_time>
                        <start_airfield>LFPB</start_airfield>
                        <end_airfield>EBBR</end_airfield>
                        <utilization>PAX</utilization>
                        <utilization_count>1</utilization_count>
                        <deleted>true</deleted>
                        <data_source_unique_id>770e8400-e29b-41d4-a716-4466554415678</data_source_unique_id>
                    </event>
                </events>
            </schedule>


+ Response 202 (text/xml)
    **Accepted**. The request to create the schedule has been accepted for processing

    + Body

+ Response 400
    **Bad request**. Invalid payload.

    + Headers

            Content-Type: text/xml

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <message>Invalid payload. The array of events was not provided or was empty</message>
            </hash>

+ Response 401 (text/xml)
    **Unauthorized**. When the token is missing or incorrect.

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <message>unauthorized</message>
            </hash>


+ Response 422
    **Unprocessable Entity**. Some of the events submitted were not valid. A list of error will be returned as shown below.

    + Headers

            Content-Type: text/xml

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <errors type="array">
                    <error>
                        <details>Utilization  is an invalid use</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                    <error>
                        <details>From airfield can't be blank</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                    <error>
                        <details>From airfield is not a valid ICAO code</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                    <error>
                        <details>To airfield can't be blank</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                    <error>
                        <details>To airfield is not a valid ICAO code</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                    <error>
                        <details>Arrival time can't be blank</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                    <error>
                        <details>Arrival time format must be yyyy-mm-ddThh:mmZ</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                    <error>
                        <details>Departure time can't be blank</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                    <error>
                        <details>Departure time format must be yyyy-mm-ddThh:mmZ</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                    <error>
                        <details>Data source unique can't be blank</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                    <error>
                        <details>Utilization count is not a number</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                </errors>
            </hash>
            
### Recreate the schedule [POST]
This action is discouraged.
Use this action to replace the entire schedule or part of the schedule defined by a date range. **The non matching events that falls in the date range will be deleted.**
This is typically best suited to situations when the events of the schedule do not have unique ids, or when events are physically deleted from the database.

> Note that the field `data_source_unique_id` is required in that case as well. If you don't have a unique id in your system, we suggest that you provide a *digest* by passing the attributes of the event to *hash function*.

+ Request (application/json)
    + Headers

            Authorization: Token token=YOUR_TOKEN
            Accept: application/json

    + Body

            {
                "schedule":
                {
                    "start_date": "2016-01-01T12:00Z",
                    "end_date": "2020-01-01T00:00Z",
                    "events": [
                      {
                        "registration_mark": "X-XXXX",
                        "start_time": "2016-06-01T13:00Z",
                        "end_time": "2016-06-01T15:00Z",
                        "start_airfield": "EGSH",
                        "end_airfield": "LFPB",
                        "utilization": "PAX",
                        "utilization_count": 3,
                        "deleted": false,
                        "data_source_unique_id": "550e8400-e29b-41d4-a716-4466554412456"
                      },
                      {
                        "registration_mark": "X-XXXX",
                        "start_time": "2016-06-03T09:00Z",
                        "end_time": "2016-06-03T11:30Z",
                        "start_airfield": "EBBR",
                        "end_airfield": "EGTK",
                        "utilization": "EMPTY",
                        "utilization_count": 0,
                        "deleted": false,
                        "data_source_unique_id": "660e8400-e29b-41d4-a716-4466554412324"
                      },
                      {
                        "registration_mark": "X-XXXX",
                        "start_time": "2016-07-04T09:00Z",
                        "end_time": "2016-07-04T11:30Z",
                        "start_airfield": "LFPB",
                        "end_airfield": "EBBR",
                        "utilization": "PAX",
                        "utilization_count": 1,
                        "deleted": true,
                        "data_source_unique_id": "770e8400-e29b-41d4-a716-4466554415678"
                      }
                    ]
                }
            } 

+ Response 202 (application/json)
    **Accepted**. The request to create the schedule has been accepted for processing

    + Body

+ Response 400
    **Bad request**. Invalid payload. ie. if the date range is not submitted or if the array of events was not provided or was empty

    + Headers

            Content-Type: application/json

    + Body

            {
              "message": "Invalid payload. The parameters start_date and end_date are not supported on this action"
            }

+ Response 401 (application/json)
    **Unauthorized**. When the token is missing or incorrect.

    + Body

            {
               "message": "unauthorized"
            }



+ Response 422
    **Unprocessable Entity**. Some of the events submitted were not valid. A list of error will be returned as shown below.

    + Headers

            Content-Type: application/json

    + Body

            {
              "errors":
                [
                    {
                        "details" : "To airfield is not a valid ICAO code",
                        "meta": {"index": 450}
                    }
                ]
            }


+ Request (text/xml)

    + Headers

            Accept: text/xml
            Authorization: Token token=YOUR_TOKEN

    + Body

            <schedule>
                <start_date>2016-01-01T12:00Z</start_date>
                <end_date>2020-01-01T00:00Z</end_date>
                <events>
                    <event>
                        <registration_mark>X-XXXX</registration_mark>
                        <start_time>2016-06-01T13:00Z</start_time>
                        <end_time>2016-06-01T15:00Z</end_time>
                        <start_airfield>EGSH</start_airfield>
                        <end_airfield>LFPB</end_airfield>
                        <utilization>PAX</utilization>
                        <utilization_count>3</utilization_count>
                        <deleted>false</deleted>
                        <data_source_unique_id>550e8400-e29b-41d4-a716-4466554412333</data_source_unique_id>
                    </event>
                    <event>
                        <registration_mark>X-XXXX</registration_mark>
                        <start_time>2016-06-03T09:00Z</start_time>
                        <end_time>2016-06-03T11:30Z</end_time>
                        <start_airfield>EBBR</start_airfield>
                        <end_airfield>EGTK</end_airfield>
                        <utilization>EMPTY</utilization>
                        <utilization_count>0</utilization_count>
                        <deleted>false</deleted>
                        <data_source_unique_id>660e8400-e29b-41d4-a716-4466554412324</data_source_unique_id>
                    </event>
                    <event>
                        <registration_mark>X-XXXX</registration_mark>
                        <start_time>2016-07-04T09:00Z</start_time>
                        <end_time>2016-07-04T11:30Z</end_time>
                        <start_airfield>LFPB</start_airfield>
                        <end_airfield>EBBR</end_airfield>
                        <utilization>PAX</utilization>
                        <utilization_count>1</utilization_count>
                        <deleted>true</deleted>
                        <data_source_unique_id>770e8400-e29b-41d4-a716-4466554415678</data_source_unique_id>
                    </event>
                </events>
            </schedule>


+ Response 202 (text/xml)
    **Accepted**. The request to create the schedule has been accepted for processing

    + Body

+ Response 400
    **Bad request**. Invalid payload. ie. if the date range is not submitted or if the array of events was not provided or was empty

    + Headers

            Content-Type: text/xml

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <message>Invalid payload. The parameters start_date and end_date are not present or not at a valid format</message>
            </hash>

+ Response 401 (text/xml)
    **Unauthorized**. When the token is missing or incorrect.

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <message>unauthorized</message>
            </hash>


+ Response 422
    **Unprocessable Entity**. Some of the events submitted were not valid. A list of error will be returned as shown below.

    + Headers

            Content-Type: text/xml

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <hash>
                <errors type="array">
                    <error>
                        <details>Data source unique can't be blank</details>
                        <meta>
                            <index type="integer">0</index>
                        </meta>
                    </error>
                </errors>
            </hash>



+ Response 202